Add PrivateMessageEvent to listen to private messages
Aust1n46/VentureChat pull request #8
Opened 2022-05-12 11:14 UTC by LOOHP

This PR adds an event to listen to private messages. It's basically the same as the earlier one but applied accordingly to 4.0.0 instead, with the usage of @Getter @Setter annotations instead, mirroring what VentureChatEvent does.

2022-12-04 03:14 UTC, Aust1n46 requested changes

2022-12-04 03:14 UTC, Aust1n46 commented on src/main/java/venture/Aust1n46/chat/api/events/PrivateMessageEvent.java
> +        super(!Bukkit.isPrimaryThread());
Would be preferable to pass this in if possible rather than making a static call.  Hurts future testability.

2022-12-04 03:14 UTC, Aust1n46 commented on src/main/java/venture/Aust1n46/chat/initators/commands/Message.java
> +				Bukkit.getPluginManager().callEvent(privateMessageEvent);
```suggestion
				plugin.getServer().getPluginManager().callEvent(privateMessageEvent);
```

2022-12-05 00:47 UTC, LOOHP commented
I've amended the changes as requested. In terms of implementing cancellation, I think it is best that you do it as `VentureChatEvent` isn't cancellable so I am not sure how you would want to approach it.

Thank you for coming back to review this PR nevertheless! :D

2022-12-06 04:36 UTC, Aust1n46 commented
> I've amended the changes as requested. In terms of implementing cancellation, I think it is best that you do it as `VentureChatEvent` isn't cancellable so I am not sure how you would want to approach it.
> 
> Thank you for coming back to review this PR nevertheless! :D

Should be able to just implement Cancellable and then check if isCancelled after firing, do nothing.  Else proceed with the existing logic.  Similar to https://github.com/Aust1n46/VentureChat/pull/49 but without any error messaging back to the player.

2022-12-06 12:13 UTC, LOOHP commented
> > I've amended the changes as requested. In terms of implementing cancellation, I think it is best that you do it as `VentureChatEvent` isn't cancellable so I am not sure how you would want to approach it.
> > Thank you for coming back to review this PR nevertheless! :D
> 
> Should be able to just implement Cancellable and then check if isCancelled after firing, do nothing. Else proceed with the existing logic. Similar to #49 but without any error messaging back to the player.

Alright, I've done just that.

2023-01-22 18:39 UTC, closed without merging